[WNMGDS-1380] Add Grid Layout guidance to the Core GitHub doc site
CMSgov/design-system pull request #1562
Opened 2022-01-29 19:32 UTC by line47

## Summary

Add updated and more detailed grid guidance to doc site

### Added
- Updated guidance and terminology for layout grid 

## How to test
- run the doc site locally with `yarn start`

2022-01-31 18:04 UTC, ericwbailey requested changes
A few questions, and some minor content suggestions.

2022-01-31 18:04 UTC, ericwbailey commented on packages/design-system-docs/src/pages/utilities/layout-grid/_grid.docs.scss
> +        <img src="{{root}}/images/grid-margins.png" class="ds-u-border--1" />
```suggestion
        <img alt="2 thin dark blue columns placed to the immediate left and right of 12 light blue columns. Screenshot." src="{{root}}/images/grid-margins.png" class="ds-u-border--1" />
```

2022-01-31 18:04 UTC, ericwbailey commented on packages/design-system-docs/src/pages/utilities/layout-grid/_grid.docs.scss
> +        <img src="{{root}}/images/layout-regions.png" class="ds-u-border--1" />
```suggestion
        <img alt="Large blue rectangles stretching through light blue grid columns to demonstrate how to create regions. The first row has two equal width regions and the second row has three equal width regions. Screenshot." src="{{root}}/images/layout-regions.png" class="ds-u-border--1" />
```

2022-01-31 19:27 UTC, line47 commented on packages/design-system-docs/src/pages/utilities/layout-grid/_grid.docs.scss
>  Offsetting columns
This gets automagically turned into a heading

2022-01-31 19:27 UTC, line47 commented on packages/design-system-docs/src/pages/utilities/layout-grid/_grid.docs.scss
> +Column spanning
This gets automagically turned into a heading

2022-01-31 19:30 UTC, line47 commented on packages/design-system-docs/src/pages/utilities/layout-grid/_grid.docs.scss
> +</div>
No I don't think we do here, this is supposed to render as HTML

2022-01-31 19:31 UTC, line47 commented on packages/design-system-docs/src/pages/utilities/layout-grid/_grid.docs.scss
>  - **Columns** determine the number of columns an item will span across, out of a possible 12 per row.
If we use 1. here this would make it an ordered list. Are you thinking these should have an order?

2022-02-02 14:44 UTC, ericwbailey commented on packages/design-system-docs/src/pages/utilities/layout-grid/_grid.docs.scss
>  - **Columns** determine the number of columns an item will span across, out of a possible 12 per row.
I was going off the previous subheading, "The grid consists of three distinct pieces". For situations like this, I find it's helpful to be explicit and enumerate.

2022-02-02 14:44 UTC, ericwbailey commented on packages/design-system-docs/src/pages/utilities/layout-grid/_grid.docs.scss
> +</div>
Ah, gotcha!

2022-02-02 14:44 UTC, ericwbailey commented on packages/design-system-docs/src/pages/utilities/layout-grid/_grid.docs.scss
> +Column spanning
Magic!

2022-02-02 14:45 UTC, ericwbailey approved these changes

2022-02-02 14:59 UTC, merged

2022-02-02 15:00 UTC, zarahzachz commented on packages/design-system-docs/src/pages/utilities/layout-grid/grid-offset.example.html
> +    <div class="ds-l-col--8 ds-u-margin-left--auto ds-u-margin-right--auto">
Could this be condensed to `.ds-u-margin-x--auto`?

2022-02-03 13:46 UTC, line47 commented on packages/design-system-docs/src/pages/utilities/layout-grid/_grid.docs.scss
> +Use the layout grid for organizing space, text, images, and other elements used in design. Following a grid while designing user interfaces (UI) provides a consistent design across various screen siz
I like the idea of removing the specific disciplines here