Migrated guidance from the DSM to the docs site for M.gov
CMSgov/design-system pull request #2047
Opened 2022-08-15 18:24 UTC by babsdenney

## Summary

[WNMGDS-1810 - Migrate Mgov DSM content into doc site](https://jira.cms.gov/browse/WNMGDS-1810)

Migrated content from the DSM to the Docs site using guidance created in this [Mural board](https://app.mural.co/t/cmsoc4625/m/cmsoc4625/1657895242729/a8e0dfa85767f39610169548df0f586845ce13c3?sender=ucf13c21d112482a4c5766770).

The following pages were not migrated as they need further instruction. 
- Spacing
- Alerts
- Layout grid

### Added

- Exceptions page to the guidelines section. 

### Changed

Added M.gov guidance to the following pages:
- Foundations
   - Typography
- Components
   - Icons
   - Buttons
   - Tooltips
   - Help drawer

Note: Transfer of guidance is not line for line from the DSM. Some of the guidance did not need to be migrated.

## How to test

- Build doc site locally
- Switch to M.gov theme
- Navigate to pages above
- Verify with DSM pages [found here](https://cms.invisionapp.com/dsm/cms/mgov-design-system)

2022-08-15 21:13 UTC, forrestbaer approved these changes
Looks good Barb! :+1:

2022-08-17 19:08 UTC, line47 commented on packages/docs/content/components/drawer.mdx
> +### Guidance
Let's move this down to the guidance section on the page that already exists and then we can also remove this duplicate header

2022-08-17 19:09 UTC, line47 commented on packages/docs/content/components/button.mdx
> +<ThemeContent onlyThemes={['medicare']}>
Let's move this down to the guidance section which is at the bottom of the page

2022-08-17 19:09 UTC, line47 commented on packages/docs/content/components/icon.mdx
> +
Let's move this to the guidance section at the bottom of the page

2022-08-17 19:10 UTC, line47 commented on packages/docs/content/components/tooltip.mdx
> +### Guidance
Let's move this to the guidance section at the bottom of the page

2022-08-17 19:12 UTC, line47 requested changes
A simple update to these pages and this should be ok to merge! Looks like the guidance should be living within the guidance sections at the bottom of the pages.

2022-08-23 18:29 UTC, babsdenney reviewed
This has been fixed.

2022-08-23 18:35 UTC, line47 commented on packages/docs/content/components/button.mdx
> +- Remove articles and use '&' instead of 'and.'
```suggestion
- Remove articles and use '&' instead of 'and'
```

2022-08-23 18:36 UTC, line47 commented on packages/docs/content/components/drawer.mdx
> +- Links are clickable.
Is this guidance needed ?`Links are clickable` ?

2022-08-23 18:37 UTC, line47 commented on packages/docs/content/components/tooltip.mdx
> +- Be a hover over interaction on desktop and click to activate on mobile.
```suggestion
- Use a hover over interaction on desktop and click to activate on mobile.
```

2022-08-23 18:37 UTC, line47 commented on packages/docs/content/components/tooltip.mdx
> +- Appear right next to the linked term.
```suggestion
- Appear next to the linked term.
```

2022-08-23 18:38 UTC, line47 commented on packages/docs/content/components/tooltip.mdx
> +- When the tool tip is just contextual help: Don't include the linked term at the top of the tool tip.
```suggestion
- When the tooltip is just contextual help: Don't include the linked term at the top of the tool tip.
```

2022-08-23 18:38 UTC, line47 commented on packages/docs/content/components/tooltip.mdx
> +- When the tool tip is just contextual help: Don't include the linked term at the top of the tool tip.
```suggestion
- When the tooltip is just contextual help: Don't include the linked term at the top of the tooltip.
```

2022-08-23 18:39 UTC, line47 commented on packages/docs/content/components/tooltip.mdx
> +- If required to include a legal disclaimer to point to Medicare glossary, the disclaimer isn't included in character count.
```suggestion
- If required to include a legal disclaimer to point to [Medicare glossary](https://www.medicare.gov/glossary), the disclaimer isn't included in character count.
```

2022-08-23 18:51 UTC, line47 commented on packages/docs/content/guidelines/exemptions.mdx
> +---
The exemptions pages are now living on Confluence and can be deleted from here! :partying\_face:

2022-08-23 18:51 UTC, line47 commented on packages/docs/content/guidelines/exceptions.mdx
> +---
The exemptions pages are now living on Confluence and can be deleted from here! :partying\_face:

2022-08-23 18:52 UTC, line47 commented
@babsdenney added a few small suggestions and deletions to make. Once that happens this should be good to merge! :tada:

2022-08-24 18:33 UTC, line47 approved these changes

2022-08-24 20:11 UTC, pwolfert commented
Jenkins doesn't seem to be reporting the test results back. I'm going to push an empty commit to trigger it again

2022-08-24 20:42 UTC, merged