[WNMGDS-2236] Initial redesign of hgov footer
CMSgov/design-system pull request #2457
Opened 2023-04-11 14:21 UTC by zarahzachz

WNMGDS-2236

2023-04-13 20:35 UTC, brentschneider requested changes
Overall spot on from a visual perspective,   
found the url on the HC.gov logo points to HHS.gov  
other than the url 👏🏼👏🏼👏🏼👏🏼 yay!

2023-04-17 16:43 UTC, pwolfert reviewed
Looking at these screenshots, there appears to be a difference in how the healthcare.gov logo aligns between Firefox and Webkit. Webkit seems wrong

2023-04-17 19:14 UTC, forrestbaer commented
Will need Labels/etc also please!

2023-04-17 19:15 UTC, pwolfert commented on packages/ds-healthcare-gov/src/styles/components/_Logo.scss
> -}
Nice, I love it when a fix involves deleting code 😄

2023-04-20 13:34 UTC, merged