[WNMGDS-2319] Storybook 7 upgrade
CMSgov/design-system pull request #2492
Opened 2023-05-08 16:46 UTC by zarahzachz

## Summary

Upgrade to Storybook 7, resolve build issues around Typescript.

See the Storybook examples still work on the [demo url](https://cmsgov.github.io/design-system/branch/WNMGDS-2319/storybook-7-upgrade).

2023-05-08 16:56 UTC, forrestbaer commented
Discovered one strange thing with the analytics menu:
![image](https://user-images.githubusercontent.com/783820/236884396-e7069129-e96d-4a06-b9aa-97463bb75330.png)

2023-05-08 17:00 UTC, forrestbaer commented
Getting 6 `test:unit` errors all relating to tooltip.

2023-05-08 18:12 UTC, forrestbaer commented
Running into issues with VRT snapshots as well, probably because of the Docs pages, I'll see if I can work through that in this branch.

2023-05-08 19:44 UTC, forrestbaer commented
I updated the VRT testing to work with the changes made and pushed the diffs it found, and hey, VRT interaction testing paying off! Take a look at `SingleInputDateField` with Picker and it no longer makes not-in-range items un-clickable, not sure how that happened. Maybe something with the story config

2023-05-08 23:54 UTC, pwolfert commented
Looks like the current CI failures are TypeScript errors that might have to do with the react types upgrades

2023-05-09 13:55 UTC, zarahzachz commented on tests/browser/snapshots/components-text-field--multiline-field-cmsgov--firefox.png
🤔 I wonder why the FF VRTs removed the resize handle from multi-line text inputs? Running it locally and I can clearly see the resizer (FF v 112)

2023-05-09 13:58 UTC, zarahzachz commented on tests/browser/snapshots/datefield--picker-interaction--cmsgov--Mobile-Chrome.png
Logic appears broken for datepicker 😢  We have the `toDate` prop set to 2/15/23, which looks like it's supposed to make all following dates disabled (as prior VRT shows). Dates are now all accessible - don't know why a SB upgrade would impact this?

2023-05-09 18:21 UTC, forrestbaer commented on tests/browser/snapshots/components-text-field--multiline-field-cmsgov--firefox.png
It's there but it's tiny!

2023-05-09 21:07 UTC, zarahzachz commented on tests/browser/snapshots/datefield--picker-interaction--cmsgov--Mobile-Chrome.png
I accidentally bumped the version of react-day-picker. This caused our local CSS to fall out of sync with the library and that's why things look broken.

2023-05-10 13:05 UTC, forrestbaer commented on tests/browser/snapshots/datefield--picker-interaction--cmsgov--Mobile-Chrome.png
So glad it was easy! Was worried storybook was doing something strange.

2023-05-10 14:34 UTC, zarahzachz commented on package.json
> +    "@playwright/test": "^1.33.0",
SB migration bumped this package and it's breaking tests in CI 😩 Addressing this issue now

2023-05-10 19:10 UTC, pwolfert requested changes

2023-05-10 19:10 UTC, pwolfert commented on .storybook/main.ts
> +  staticDirs: ['./static/', '../packages/design-system/src'],
This actually clobbers a fix I recently made, which was removing the `'../packages/design-system/src'` item

2023-05-10 19:29 UTC, forrestbaer approved these changes

2023-05-10 19:50 UTC, pwolfert approved these changes
LGTM 🎉

2023-05-10 20:52 UTC, merged