[WNMGDS-2825] Fix release tagging
CMSgov/design-system pull request #3158
Opened 2024-07-15 23:01 UTC by pwolfert

## Summary

- The release script no longer uses Lerna. Instead it manually creates the publish commit and tags.
- The release script no longer asks for version changes for individual packages. Instead, you just select the "release type" from a list, and it applies the change to all packages appropriately.
- Fixed the `--undo` sub-command because we only try to delete tags that we created (because we're in charge of that now).

## How to test

1. Check out the branch
2. Create your own test branch off of it like `git branch -b "your-test-branch-name"` so it doesn't push changes to origin and cause the Jenkins to do extra work with CI tests
3. Run the release script. Check the changes it made for correctness
4. Undo the release with `yarn release --undo`
5. Delete your test branch

## Checklist

- [x] Prefixed the PR title with the [Jira ticket number](https://jira.cms.gov/projects/WNMGDS/) as `[WNMGDS-####] Title` or [NO-TICKET] if this is unticketed work.
- [x] Selected appropriate `Type` (only one) label for this PR, if it is a breaking change, label should only be `Type: Breaking`
- [x] Selected appropriate `Impacts`, multiple can be selected.
- [x] Selected appropriate release milestone

2024-07-16 18:01 UTC, zarahzachz commented
Do we still need Lerna now that the script's been updated?

2024-07-16 20:42 UTC, pwolfert commented
About the GPG issues, maybe we can troubleshoot in our engineering meeting tomorrow, since others were also experiencing this error. I'm wondering if there's a setting in `git` that needs to be set, since I know you have GPG.

2024-07-17 18:33 UTC, zarahzachz commented on package.json
> -    "lerna": "^5.6.2",
🤌 that's a nice deletion!

2024-07-18 15:07 UTC, zarahzachz approved these changes

2024-07-22 23:41 UTC, kim-cmsds requested changes
While testing locally, I forgot to comment out the two `git push` commands in the release script, which means we'll want to remove this commit (4be137c499f8bfa35db5d4e74a29bd68b3d67334) before merging. Other than that, this looks great.

2024-07-22 23:57 UTC, pwolfert commented
Hey, @kim-cmsds, you should be able to run `yarn release --undo` to remove it and its branch

2024-07-23 00:07 UTC, kim-cmsds approved these changes
Thank you for the assist, @pwolfert! Now that tagging and the undoing of a release command have been thoroughly tested, this looks good to me!

2024-07-23 00:22 UTC, merged